name: Build Wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          if [ "${{ matrix.os }}" == "windows-2022" ]; then
            choco install -y make
          fi
          python -m pip install -U pip
          pip install cibuildwheel
          pip install -r requirements.txt
          if [ "${{ matrix.os }}" == "ubuntu-20.04" ]; then
            wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
          else
            curl -O https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-4.0.2.tar.gz
          fi
          tar -xvf ./openmpi-4.0.2.tar.gz
          ./openmpi-4.0.2/configure --prefix="/home/${USER}/.openmpi"
          cd src
          ls
          aclocal
          libtoolize
          automake --add-missing
          autoconf
          ./configure --with-mpi --with-silent
          make
        shell: bash

      - name: Build wheels
        run: |
          pip wheel .
          cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse
