name: Test OpenBTMixing in Anaconda
env:
  CLONE_PATH:   ${{ github.workspace }}
  PKG_ROOT:     ${{ github.workspace }}/openbtmixing_pypkg
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #####----- FULL TESTING WITHOUT COVERAGE
  test_pypkg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        mpi_impl: ["openmpi"]
        python-version: ["3.12"]

    steps:
    #####----- SETUP TESTING ENVIRONMENT
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Checkout OpenBTMixing
      uses: actions/checkout@v4
    - name: Conda info
      shell: bash -el {0}
      run: |
        which python
        which pip
        python --version
        conda info
        conda list
        python -m pip list
    - name: Install MPI implementation via mpi4py
      shell: bash -el {0}
      run: |
        conda install -c conda-forge mpi4py openmpi
        conda list
        which mpicc
        mpicc -show
