name: Determine OpenBTMixing Python Coverage
env:
  CLONE_PATH:   ${{ github.workspace }}
  PKG_ROOT:     ${{ github.workspace }}/openbtmixing_pypkg
  VENV_PATH:    ${{ github.workspace }}/local/venv
  MESON_VENV:   ${{ github.workspace }}/local/venv/meson
  LOCAL_BIN:    ${{ github.workspace }}/local/bin
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #####----- FULL TESTING WITHOUT COVERAGE
  test_pypkg:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    #####----- SETUP TESTING ENVIRONMENT
    - name: Checkout OpenBTMixing
      uses: actions/checkout@v4
    - name: Install meson dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install ninja-build
    - name: Install mpich
      run: |
          sudo apt-get -y install mpich
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Python dependencies
      run: |
        $CLONE_PATH/.github/workflows/setup_base_python.sh ${{ runner.os }}
    - name: Install latest meson
      run: |
        mkdir -p $VENV_PATH
        python -m venv $MESON_VENV
        . $MESON_VENV/bin/activate
        python -m pip install --upgrade pip
        python -m pip install meson>=1.6.0
        mkdir -p $LOCAL_BIN
        ln -s $MESON_VENV/bin/meson $LOCAL_BIN
        echo "$LOCAL_BIN" >> "$GITHUB_PATH"

    ##-- Run full test suite with coverage
    - name: Measure coverage-by-line
      run: |
        pushd $PKG_ROOT
        tox -r -e coverage,report
        popd
