name: Test OpenBTMixing Python Package
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #####----- FULL TESTING WITHOUT COVERAGE
  test_pypkg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        mpi_impl: ["openmpi"]
        python-version: ["3.9"]

    steps:
    #####----- SETUP TESTING ENVIRONMENT
    - name: Checkout OpenBTMixing
      uses: actions/checkout@v4
    - name: Install autotools
      run: |
        brew install autoconf
        brew install autoconf-archive
        brew install automake
        brew install libtool
    - name: Install ${{ matrix.mpi_impl }}
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi_impl }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install wheel
    - name: Install eigen dependency
      run: |
        # C++ Header only => no build here! 
        git clone https://gitlab.com/libeigen/eigen.git

    #####----- BUILD WHEEL FROM SCRATCH & INSTALL
    # Prefer full end-to-end test of binary wheels rather than testing in
    # local clone alone
    - name: Build OpenBTMixing binary wheel
      run: |
        echo " "
        echo "Log Software Environment"
        echo "-------------------------------------------------"
        echo "CC=$CC"
        echo "CXX=$CXX"
        echo "MPICC=$MPICC"
        echo "MPICXX=$MPICXX"
        echo " "
        which mpicc
        mpicc -show
        echo " "
        which mpicxx
        mpicxx -show
        echo " "
        which python
        which pip
        python --version
        pip list
        echo " "
        glibtoolize --version
        aclocal --version
        automake --version
        autoconf --version
        echo " "
        echo "Setting up build system"
        echo "-------------------------------------------------"
        pushd src
        echo "libtoolizing ..."
        glibtoolize
        echo "aclocalizing ..."
        aclocal
        echo "automaking ..."
        automake --add-missing
        echo "autoconfing ..."
        autoconf
        echo " "
        echo "Configure OpenBT"
        echo "-------------------------------------------------"
        ./configure --with-mpi --with-silent
        echo " "
        echo "Make & install OpenBT CLTs"
        echo "-------------------------------------------------"
        make clean install
        popd
        echo " "
        echo "Building binary wheel"
        echo "-------------------------------------------------"
        pip wheel .
        echo " "
